language: python

before_script:
- pip install 'tox!=2.4.0,>=2.3'

# By default travis clones the rpc-openstack repo
# with --depth set to 50, creating a shallow clone.
# However, reno typically needs more (or all) of the
# history to properly traverse the commit history
# and generate release notes. This section deletes
# the shallow clone that travis creates, then clones
# the full repository
install:
  - git clone --recursive https://github.com/rcbops/rpc-openstack.git rcbops/rpc-openstack
  - cd rcbops/rpc-openstack
  - "if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then git fetch origin +refs/pull/$TRAVIS_PULL_REQUEST/merge && git checkout -qf FETCH_HEAD; else git checkout -qf $TRAVIS_COMMIT; fi"

script: tox

# Send notifications to #rpc-github in Slack
notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    secure: PMkX4ttSc5yaEKn1JYu1zf5SuE6kX0zoCv09wZI1npgYDqod72bxQBSWxYYre8/BCF9Te2UmuYIGtHxtNnvquwdfzHKJBEhpIcHJYWmBb1lNLC391stRPt2lePp5/kt/W2Ath1lhXoOZLIGZ4Akyj2S7alKlMWaqedApWOtBtQk=

matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=ansible-lint
    - python: 2.7
      env: TOXENV=releasenotes
    - python: 2.7
      env: TOXENV=bashate
    - python: 2.7
      env: TOXENV=release-script

sudo: false
