---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Get defcore tests and set tempest_test_whitelist fact
- name: Get defcore tests and set tempest_test_whitelist fact
  hosts: utility_all[0]
  gather_facts: no
  user: root
  tasks:
    - name: Get defcore test list from defcore repo
      get_url:
        url: "{{ defcore_url }}"
        dest: "/opt/defcore_tempest_list_{{ version_number }}"
      delegate_to: localhost

    - name: Set fact for defcore json file
      set_fact:
        defcore_json_file: "{{ lookup('file', '/opt/defcore_tempest_list_'~version_number) | from_json }}"

    - name: Set fact for defcore tests
      set_fact:
        defcore_tests: "{{ defcore_tests|default([]) + item.tests.keys() }}"
      with_items: "{{ defcore_json_file['capabilities'].values() }}"

    - name: Set tempest_test_whitelist fact
      set_fact:
        tempest_test_whitelist: "{{ tempest_test_whitelist|default([]) + defcore_tests }}"
  tags:
    - tempest_install
  vars:
    # 2017.01 corresponds to Ocata
    version_number: "2017.01"
    defcore_url: "https://raw.githubusercontent.com/openstack/defcore/master/{{ version_number }}.json"

# Run the tempest playbook to install tempest
- include: ../openstack-ansible/playbooks/os-tempest-install.yml
  tags:
    - tempest_install
  vars:
    tempest_run: no

# Run the tempest tests from the os_tempest role
- name: Run tempest tests from the os_tempest role
  hosts: utility_all[0]
  gather_facts: no
  user: root
  tags:
    - tempest_execute_tests
  tasks:
    - name: Run Tempest Tests
      include_role:
        name: os_tempest
        tasks_from: tempest_run
